title: bloggo
author: aprajita
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 yo! this is my blog. I enjoy writing more than anything.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
